### ISSUE TITLE
Cannot instal vertical-pod-autoscaler in AWS EKS

### ISSUE THREAD

**Issue by TabakM4n** [cowboysysop/charts#114]
Hello

I am using AWS EKS and I had previously installed vertical-pod-autoscaler
Now I am trying to update it to the latest version but I am getting this error.

`Error: chart requires kubeVersion: >=1.17 which is incompatible with Kubernetes v1.21.5-eks-bc4871b`

I tried to overwrite `kubeVersion` in values with `1.21.5` and `1.21` and did not work.

I was able to install it after helm pull and removing `kubeVersion` from `Chart.yaml` and manually installing the release from the folder

Thanks

**Comment by sebastien-prudhomme** [comment]
Hi @TabakM4n, it seems this is a known issue with EKS : https://github.com/helm/helm/issues/10375

I don't know what to do, if AWS is not respecting semantic versionning.

Can you test and confirm that using `>=1.17-0` works fine?

**Comment by simone201** [comment]
I'm facing the same issue, adding `>=1.17-0` to `kubeVersion` in the chart values doesn't change anything on my side. Any idea on how to fix it without downloading the chart sources?

**Comment by sebastien-prudhomme** [comment]
@simone201 Can you give me your Helm version and EKS version?

**Comment by sebastien-prudhomme** [comment]
@TabakM4n @simone201 I've moved the compatible Kubernetes versions in an annotation, see #115

**Comment by simone201** [comment]
Updated to 4.0.2 version of the chart, now working flawlessly! Just fyi, using Helm `3.8.0` on EKS `v1.21.5-eks-bc4871b`.

**Comment by TabakM4n** [comment]
@sebastien-prudhomme It worked with chart 4.0.2
