### ISSUE TITLE
VPA Certificate validity duration

### ISSUE THREAD

**Issue by qqmelanie** [cowboysysop/charts#161]
Hello,
First of all, thank you for your work!
We're using VPA chart and it would be very useful to have ability to set certificate validity duration. 
At the moment certificates are valid for 365 days and it's an issue for long-lived clusters, even though extended validity can be a security concern.
We would love to submit a PR if you're interested in such changes.

Thanks.

https://github.com/cowboysysop/charts/blob/6190d9e04b342f3bc9fb795d32fb9c5e0731501b/charts/vertical-pod-autoscaler/templates/admission-controller/tls-secret.yaml#L3-L6

**Comment by sebastien-prudhomme** [comment]
Hi @qqmelanie, in these charts I try to copy what Bitnami is doing in their charts: https://github.com/bitnami/charts/tree/master/bitnami

Each time they need certificates they use a fixed value of 365 days for the default auto-signed certificate, that's the reason I also use 365 days.

For your need, what you can do is:
* generating your own certificates (CA and admission controller certificate) and configure `admissionController.tls.*` parameters (in PEM format)
* generating your own secret outside of the chart and use `admissionController.tls.existingSecret`. You can use a tool such as `cert-manager` if you have yet this tool: https://cert-manager.io/

The only requirement is to have a Common Name in the certificate with the admission controller service name : `vpa-webhook.<namespace>.svc`

**Comment by qqmelanie** [comment]
Hey! Got it, thanks. `cert-manager` is a great tool, but I thought there can be an easier way. 
Anyway, thanks, I'm closing the issue.
