### ISSUE TITLE
Add podLabels to deployments

### ISSUE THREAD

**Issue by verymahler** [cowboysysop/charts#18]
I would like to be able to add a list of custom labels to my deployment.

See my pull request here: https://github.com/cowboysysop/charts/pull/17

This allows me to deploy this (for example the **mongo-express**) chart in my organisation and have it communicate the the **mongodb** pod. There is a network security policy that restricts communication between pods if they are not labeled correctly.

**Comment by sebastien-prudhomme** [comment]
Fixed in PR #19

I also used ```podLabels``` for the configuration but it's a hash and not an array as in your PR.

The new chart version is ```1.1.0``` to be conform with semantic versioning.

I let you close this issue.

**Comment by verymahler** [comment]
Thanks for the quick update. I'll be able to test this early tomorrow morning. I'll close the issue immediately after that.
