### ISSUE TITLE
Add option to use cert-manager to manage certificate for VPA admission controller

### ISSUE THREAD

**Issue by mkjpryor** [cowboysysop/charts#268]

**Comment by sebastien-prudhomme** [comment]
Hi @mkjpryor, cert-manager is not directly integrated but you can yet use `admissionController.tls.existingSecret` to use a secret generated by cert-manager.

**Comment by sebastien-prudhomme** [comment]
cert-manager resource can also be added with the `extraDeploy` value.

Maybe one day I will add direct support for cert-manager but for now I'm closing this issue.
