### ISSUE TITLE
[VPA] Argocd CRD sync issue

### ISSUE THREAD

**Issue by piotrreszke-scalac** [cowboysysop/charts#28]
I'm having a problem with using VPA chart on ArgoCD. The `verticalpodautoscalers.autoscaling.k8s.io` CRD cannot reach Synced status because of the `required` field. I suspect empty array is the default value for this field and K8s just it then causing the difference in specs, which ArgoCD is constantly trying to reconcile. I think this field can be easily removed.

Screenshot:
![image](https://user-images.githubusercontent.com/35028977/83022237-809c8280-a02b-11ea-89f1-3312e038febc.png)

**Comment by sebastien-prudhomme** [comment]
I'm also using ArgoCD with most of my charts, except this one and so didn't notice the problem. Thanks.

Will fix that.

**Comment by sebastien-prudhomme** [comment]
Fixed in #29
