### ISSUE TITLE
VPA 0.12 is not compatible with k8s 1.21

### ISSUE THREAD

**Issue by cartucciam** [cowboysysop/charts#345]
https://github.com/cowboysysop/charts/commit/794c87ef211bbd7eb112c4035df2d32c513b4d5e updates the chart to v6 and the app to 0.12 but 0.12 is only compatible with 1.25+ whereas the chart claims 1.21 support

https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#compatibility

**Comment by sebastien-prudhomme** [comment]
Hi @cartucciam, the official doc is not always correct.

I can confirm that the recommender is working fine on version 1.21. The updater seems to need version 1.22.

On what version of Kubernetes have you seen a problem?

**Comment by cartucciam** [comment]
Hi @sebastien-prudhomme, thanks for answering this, we had issues running the chart on  
1.21, the eviction stopped working complaining of a legacy API version

**Comment by cartucciam** [comment]
We fixed this by setting the updater image back to `0.9.2`. The issue remains though as the default values of the chart aren't consistent with its targeting 1.21

**Comment by sebastien-prudhomme** [comment]
I've fixed the Kubernetes minimum version in #349.

**Comment by cartucciam** [comment]
> I've fixed the Kubernetes minimum version in #349.

Thanks!!!
