### ISSUE TITLE
PR on the official kubernetes repo

### ISSUE THREAD

**Issue by rileyai-dev** [cowboysysop/charts#359]
@sebastien-prudhomme Thank you so much for your contribution. It would be fantastic if you offer your chart to the official kubernetes repo (https://github.com/kubernetes/autoscaler). It would make it more sustainable for production systems.

What do you think?

**Comment by sebastien-prudhomme** [comment]
See this issue in the official project: kubernetes/autoscaler#3068

**Comment by rileyai-dev** [comment]
That's actually the thread that brought me to your project! 

What if you directly submit a PR?

**Comment by sebastien-prudhomme** [comment]
Because the project has some maintainers and it seems having an Helm chart is not a priority.

**Comment by rileyai-dev** [comment]
Definitely not their priority but we can: forcer le destin!

**Comment by sebastien-prudhomme** [comment]
Sorry to close this one, I don't want to go further.
