### ISSUE TITLE
Make mongo-express service.nodePort configurable 

### ISSUE THREAD

**Issue by DanielBican** [cowboysysop/charts#37]
I am using mongo-express for a personal project and I am really happy with it. Great work:)
There is a small enhancement that I would benefit from, namely to make the service.targetPort configurable. I am using service.type=NodePort.

**Comment by sebastien-prudhomme** [comment]
This is a change i know i need to do, thanks to recall me :-)

**Comment by sebastien-prudhomme** [comment]
@DanielBican  I've misread your need. I thought you want to customize service nodePort. What is your use case of having a custom targetPort?

**Comment by DanielBican** [comment]
You got it right actually. I need a customizable nodePort. Should I edit
the issue title and description?

**Comment by sebastien-prudhomme** [comment]
This is fixed in #38
