### ISSUE TITLE
Support Mongo express 1.0.0

### ISSUE THREAD

**Issue by gong4soft** [cowboysysop/charts#373]
MongoExpress has already released a few month ago, any plan to support V1.0.0, which support MongoDB 6.xx version.

https://github.com/mongo-express/mongo-express/releases/tag/v1.0.0

Thanks,

**Comment by sebastien-prudhomme** [comment]
I'm Just waiting for a new Docker image: https://hub.docker.com/_/mongo-express/tags

Will be done in #166
