### ISSUE TITLE
VPA repository switch from `k8s.gcr.io` to `registry.k8s.io`

### ISSUE THREAD

**Issue by tviaud** [cowboysysop/charts#394]
Following the deprecation announcement of `k8s.gcr.io`  and the move to `registry.k8s.io` by the Kubernetes project, it would be nice to update the repositories in the VPA helm chart to switch to this as well.

This will break future updates to the VPA helm chart in the future.

* `k8s.gcr.io/autoscaling/vpa-admission-controller` -> `registry.k8s.io/autoscaling/vpa-admission-controller`
* `k8s.gcr.io/autoscaling/vpa-recommender` -> `registry.k8s.io/autoscaling/vpa-recommender`
* `k8s.gcr.io/autoscaling/vpa-updater` -> `registry.k8s.io/autoscaling/vpa-updater`

Official blog post: https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/

(cluster-autoscaler helm chart has been updated this way: https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/values.yaml#L231)

Thanks in advance :)

**Comment by sebastien-prudhomme** [comment]
Yes, I've seen that. It seems they forgot to make the change in the latest stable release of VPA. The change is only in the master branch for now.

**Comment by sebastien-prudhomme** [comment]
Fixed in #395, be careful some image parameters have changed.
