### ISSUE TITLE
Enable sequelize support in the lighthouse-ci

### ISSUE THREAD

**Issue by fsmaia** [cowboysysop/charts#51]
Firstly, congratulations on this life saver chart.

In the [lighthouse-ci configuration docs](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#storagesequelizeoptions), they mention that is possible to configure [sequelize](https://sequelize.org/) to provide additional storage options to the [server](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#server) command, such as an external host database:
> **`storage.sequelizeOptions`**
> Additional raw options object to pass to sequelize. Refer to the sequelize documentation for more information on available settings.

Currently, the [server docker image](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/recipes/docker-server/Dockerfile) uses `npm start` as the entry point, which represents this command:
```bash
$ lhci server --config=./lighthouserc.json
```

And then it is possible to customize it by passing an extra `--storage.sequelizeOptions`, something like:
```bash
$ npm start -- --storage.sequelizeOptions
```
We could add the [sequelize](https://sequelize.org/) options to the chart values, and then configuring them as `args` in the container initialization.

What do you think?

**Comment by sebastien-prudhomme** [comment]
Great, I was planning SQL database support but I was waiting for someone that need it :-)

In fact you need to add other arguments, sequelizeOptions is only for tuning Sequelize.

What I plan to do is adding MySQL and PostgreSQL support either by using integrated subcharts or by referencing external databases as you want. Do you need more things?

By the way, for generic configuration there is this PR #50 that is yet not closed..

**Comment by fsmaia** [comment]
> What I plan to do is adding MySQL and PostgreSQL support either by using integrated subcharts or by referencing external databases as you want. Do you need more things?

Amazing, that's exactly what I need! :rocket:

May I help somehow?
