### ISSUE TITLE
Add option to serve mongo-express in a subdirectory

### ISSUE THREAD

**Issue by enyo** [cowboysysop/charts#52]
I'd like to use this chart, but serve mongo express in a subdirectory. I have used an ingress rewrite for that, but then all CSS and JS files fail to load because it tries to load them from `/` instead of `/subdir`

**Comment by jr200** [comment]
I have the same issue, ideally we should be able to set `ME_CONFIG_SITE_BASEURL` somewhere, but theres no option to send through extra env vars...

**Comment by sebastien-prudhomme** [comment]
Fixed by #55, there is a new option `siteBaseUrl` in the chart for configuring `ME_CONFIG_SITE_BASEURL` environment variable in the deployment.
