### ISSUE TITLE
[vertical-pod-autoscaler] CRD job is missing template labels

### ISSUE THREAD

**Issue by QuentinBisson** [cowboysysop/charts#526]
Hello @sebastien-prudhomme the new CRD job that you introduced some time back is missing job template labels as can be seen here https://github.com/cowboysysop/charts/blob/6bbde64075b77a642be1492bf0134c95beccc628/charts/vertical-pod-autoscaler/templates/crds/job.yaml#L17 so it is difficult to target this job with a network policy.

Could you add it the same way you added them for the deployments in the chart? https://github.com/cowboysysop/charts/blob/6bbde64075b77a642be1492bf0134c95beccc628/charts/vertical-pod-autoscaler/templates/admission-controller/deployment.yaml#L23

**Comment by sebastien-prudhomme** [comment]
@QuentinBisson sure, I will fix it soon.

**Comment by sebastien-prudhomme** [comment]
Implemented in #527

**Comment by QuentinBisson** [comment]
Thank you :)
