### ISSUE TITLE
Support for priorityClassName

### ISSUE THREAD

**Issue by wmgroot** [cowboysysop/charts#54]
Hello. We'd like to leverage this chart to install VPA in our clusters, but need to ensure that random workloads in the cluster do not deschedule the VPA pods by using priority classes.

I opened a PR before reading your README about not accepting PRs, but I believe the change is very straightforward.
https://github.com/cowboysysop/charts/pull/53

**Comment by sebastien-prudhomme** [comment]
Hi, i've done what you need for all the charts in the repository in #57

**Comment by wmgroot** [comment]
Thanks, appreciated.
