### ISSUE TITLE
Unclear appVersion references in vertical-pod-autoscaler HelmChart Image tags

### ISSUE THREAD

**Issue by XiaoshiWang** [cowboysysop/charts#560]
The image tags specified in the values.yaml were not updated for a long time and now in the current version all with 1.0.0
Example tags:

- https://github.com/cowboysysop/charts/blob/master/charts/vertical-pod-autoscaler/values.yaml#L51
- https://github.com/cowboysysop/charts/blob/master/charts/vertical-pod-autoscaler/values.yaml#L51

It is hard to derive if this is really the appVersion of the chart. Maybe they can be just left empty and derived from appVersion in Chart.yaml?

**Comment by sebastien-prudhomme** [comment]
Renovate is used to update all image versions. The appVersion is just metadata, I really don't want to use that metadata to build image versions. Sometime the tag is not the same and I'm also using images with other versions not directly related to the main app.

**Comment by sebastien-prudhomme** [comment]
I also try to follow application lifecycle. The product has just been updated from 0.14 to 1.0, I guess it's now considered stable enought.
