### ISSUE TITLE
Templatize toggling hostNetwork on admissionController for the vertical pod scaler chart

### ISSUE THREAD

**Issue by RadOctocode** [cowboysysop/charts#594]
Hi Folks,
    I would like to be able to toggle hostNetwork on the admissionController template for the vertical pod autoscaler chart. [I made the change before realizing you do not accept pull requests.](https://github.com/cowboysysop/charts/pull/591) Is there anyway I can get this change added to the vertical pod autoscaler chart?

**Comment by sebastien-prudhomme** [comment]
Hi @RadOctocode are you using EKS? If yes, can you try changing the container port as explained in #402.

**Comment by sebastien-prudhomme** [comment]
Fixed by #633
