### ISSUE TITLE
checksum/secret is recalculated every helm diff causing helm to mark it as changed

### ISSUE THREAD

**Issue by trevore** [cowboysysop/charts#61]
The checksum/secret changes every time we diff the chart which causes it to show as changed. This causes problems for our CI/CD process. I'm not really sure what this checksum is used for but I'm wondering if there is a way to avoid it changing every run. Maybe we could use the existing certs instead of generating new certs every run or something like that?

This is the line in question. 

https://github.com/cowboysysop/charts/blob/8530dcb2c57ba5f7acce9ae774c3b11719fb3f19/charts/vertical-pod-autoscaler/templates/admission-controller/deployment.yaml#L20

Thank you for maintaining this helm chart and taking a moment to consider my issue.

**Comment by sebastien-prudhomme** [comment]
Hi @trevore, you're right, if you don't want that behavior you need to setup TLS values `admissionController.tls.caCert`, `admissionController.tls.cert` and `admissionController.tls.key`.

You can also use an existing secret with the right keys (see templates/admission-controller/tls-secret.yaml).

The checksum is used to ensure pod is restarted when TLS values change.

**Comment by trevore** [comment]
Hi @sebastien-prudhomme, thank you for replying to me. I see the option to include an existing secret. The problem for us is that would mean checking secrets into a Git repo, which we want to avoid. We could also include it in a variable in the CI/CD platform but that's really not ideal either. Ideally helm would detect their existence on the cluster but that's a bit complicated in this case.

We just had the VPA admissions controller crash, I suspect it's related to the fact we are regularly triggering multiple helm deploys a day because of this. Unfortunately it did not log anything in the crash so we are just guessing.

This checksum is a bit of a circular loop, it's only changing the certs because of it. It seems fine to rotate the certs every time this chart is changed but unless we statically define the certs, they are changed every single diff. I'm wondering how you would feel about adding an option to suppress this checksum? I'm happy to submit a PR if you are open to it.

**Comment by sebastien-prudhomme** [comment]
Hi @trevore, this checksum is a good practice in Helm chart either for ConfigMap or Secret and I don't want to change that.

Giving the option to use an existing secret is also a good practice.

You can use some tools like this to handle secret privacy in Git: https://github.com/bitnami-labs/sealed-secrets

Another option is to manage the TLS certificate with cert-manager, the secret that will be generated when creating a Certificate resource is compatible with the one used by the vertical-pod-autoscaler chart as long as you use the correct CN (Common Name): https://cert-manager.io/

**Comment by wellermann** [comment]
We moved it into Cert Manager. Thanks for taking the time to talk with me. This can be closed.
