### ISSUE TITLE
dolibarr: add extraInitContainer

### ISSUE THREAD

**Issue by DrummyFloyd** [cowboysysop/charts#617]
because sometimes you have external DB and need to wait is up.

**Comment by sebastien-prudhomme** [comment]
Hi @DrummyFloyd, I've added a similar thing in another chart, based on wait4x: https://github.com/atkrad/wait4x

I forgot to add it in all the charts.

**Comment by sebastien-prudhomme** [comment]
Implemented in #623. Managing of generic init containers will wait.
