### ISSUE TITLE
Flowiseai - Logs persistence

### ISSUE THREAD

**Issue by danielstankw** [cowboysysop/charts#658]
Hi, 
I am attempting to make logs persistent in Flowiseai.
To my understanding flowiseai allows to define a log save path using env variable called: LOG_PATH.
How can I modify the values.yaml to enable persistence of logs? 

I have a PVC and PV defined but to save logs into them I would need to have a volume mount field in the chart.

**Comment by sebastien-prudhomme** [comment]
Hi @danielstankw , you should try to use the `extraEnvVars` value for now and point to something like "/data/logs". It will use the default PVC if you activate persistence.

**Comment by sebastien-prudhomme** [comment]
Hi @danielstankw , FYI you also can add an extra volume for logs in the next version of the chart.
