### ISSUE TITLE
flowise: postgresql backup pod fails with `Temporary failure in name resolution` if networkPolicy is enabled

### ISSUE THREAD

**Issue by lalmeras** [cowboysysop/charts#671]
Flowise chart, when postgresql database and backup cronjob is used, produces a non-working configuration.

Backup pod fail with `Temporary failure in name resolution` as postgresql service hostname cannot be resolved.

`networkPolicy: true` is the default setup for bitnami/postgresql. https://github.com/bitnami/charts/blob/eba61bd31721b220163f799a5694d234f677ae1b/bitnami/postgresql/values.yaml#L1328

```yaml
postgresql:
  backup:
    cronjob:
      networkPolicy:
        enabled: true
```

* If networkPolicy is disabled, backup works as expected.
* If networkPolicy is enabled, backup fails with DNS failure.

This is a bitnami known and fixed issue : https://github.com/bitnami/charts/pull/25534. bitnami/postgresql 15.2.13 includes this PR and modifies networkPolicy to allow DNS trafic. Can you update flowise chart to bitnami/postgresql 15.2.13 ?

**Comment by sebastien-prudhomme** [comment]
Bonjour Laurent, for sure I will do it.

**Comment by lalmeras** [comment]
Thank you for your feedback.

**Comment by sebastien-prudhomme** [comment]
Done in #672 with the update to version 1.8.2
