### ISSUE TITLE
web browser typeerror?

### ISSUE THREAD

**Issue by bb331000** [cowboysysop/charts#689]
I've restarted my service on Render and updated my branch and also tried in Safari and Firefox.  Still getting this error. 

Logs
 2024-07-10 21:21:03 [ERROR]: [server]: Error: Error buildAgentGraph - TypeError: Cannot use 'in' operator to search for 'input_schema' in {{webBrowser_0.data.instance}}
Error: Error buildAgentGraph - TypeError: Cannot use 'in' operator to search for 'input_schema' in {{webBrowser_0.data.instance}}.                                                   

Is this something to do with how Flowise is handling data from a web browser component?

**Comment by sebastien-prudhomme** [comment]
Hi @bb331000 I don't see any indication that Render can run Kubernetes Helm chart. If you're just using the Docker image, please open a bug in the upstream project: https://github.com/FlowiseAI/Flowise
