### ISSUE TITLE
feature request: support SSL for external postgres connections

### ISSUE THREAD

**Issue by dominicdejacomo** [cowboysysop/charts#70]
Please consider adding support for SSL on external postgres connections, some newer cloud offerings (I'm looking at you Azure Postgres Flexible Servers) are SSL only.

perhaps externalPostgres.ssl='true'

Information on needed env vars can be found at https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#custom-sequelize-configuration)

**Comment by sebastien-prudhomme** [comment]
Hi @dominicdejacomo, as I said in the README, I want to keep some consistency between all the charts.

Your PR is only for one use case in one of the chart.

What I can do is adding an `extraEnvVars` parameter to all the charts so that you can use the right env variables that enable SSL mode.

**Comment by dominicdejacomo** [comment]
Hey @sebastien-prudhomme, 

I did see the README and had no expectation of the pull being accepted, it seemed like a convenient way to share a working config if you decided to build on it.

The extraEnvVars parameter will absolutely allow me to get the same functionality with more flexibility.

Thanks for taking a look!

**Comment by sebastien-prudhomme** [comment]
@dominicdejacomo Fixed by PR #74
