### ISSUE TITLE
Update VPA to 1.2.0 version

### ISSUE THREAD

**Issue by BestChinchilla** [cowboysysop/charts#713]
VPA project is released to 1.2.0 version: [PR](https://github.com/kubernetes/autoscaler/pull/7130)
Is this chart planned to update? In 1.2.0 ver. there's a useful argument `ignored-vpa-object-namespaces` that I really want to use: [Docs](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#limiting-which-namespaces-are-used)

**Comment by sebastien-prudhomme** [comment]
Hi @BestChinchilla, it will be done in september. For now you can change the values of the chart release to use the new image and to add some extra args.
