### ISSUE TITLE
Finer labelling on mongo-express ?

### ISSUE THREAD

**Issue by speedfl** [cowboysysop/charts#75]
Hello,

Some needs to have a finer label handling (specific for services, ingress or even shared by all the objects)

Here is some example with bitnami/mongodb:
https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L35
https://github.com/bitnami/charts/blob/master/bitnami/memcached/values.yaml#L44
https://github.com/bitnami/charts/pull/6815

Would it be possible to add this feature in the mongo-express charts ?

Here is the link to a pull request:

https://github.com/cowboysysop/charts/pull/73

You can reuse my fork to have a starter

Thanks in advance

**Comment by sebastien-prudhomme** [comment]
As I'm trying to mimic Bitnami best practices, are common labels enough?

**Comment by speedfl** [comment]
Hey.
Indeed it perfect.
Thanks a lot

**Comment by sebastien-prudhomme** [comment]
Hi @speedfl, the feature is implemented by PR #76
