### ISSUE TITLE
[VPA] improve TLS certificate generation for GitOps compatibility

### ISSUE THREAD

**Issue by r0bj** [cowboysysop/charts#768]
Currently, each execution of the vertical-pod-autoscaler Helm chart generates new certificates using the genSignedCert and genCA functions. This approach is not GitOps-friendly and can cause issues with tools like Argo CD, which detect these changes and mark the application as OutOfSync.

Problem Details
- Non-Idempotent Deployments: Regenerating certificates on every Helm execution leads to non-idempotent deployments, causing unnecessary diffs in GitOps workflows.
- Argo CD OutOfSync Issues: Tools like Argo CD compare the desired state (from Git) with the live cluster state. Regenerating certificates each time results in constant discrepancies, triggering OutOfSync statuses.
- GitOps Incompatibility: This behavior hinders seamless integration with GitOps practices, where the goal is to have declarative, version-controlled infrastructure and applications.

Proposed Solution
- Use a Pre-install Hook: Implement a Helm pre-install hook to run a Kubernetes Job responsible for generating the certificates.
- Populate Kubernetes Secret: The Job would generate the certificates and store them in a Kubernetes Secret, which can be referenced by the chart.
- Avoid Regeneration on Each Deployment: By isolating certificate generation to a one-time job (unless explicitly re-run), we prevent unnecessary changes during regular Helm upgrades or reapplications.

**Comment by sebastien-prudhomme** [comment]
Hi, you can yet use `admissionController.tls.existingSecret` to reference a secret generated outside of the Helm chart.

**Comment by r0bj** [comment]
Yes, I could use admissionController.tls.existingSecret, but that would require additional logic or relying on cert-manager to populate the secret. This approach increases complexity and introduces an unnecessary dependency.

**Comment by arichtman-srt** [comment]
Related: #827
