### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by danielstankw** [cowboysysop/charts#794]
I am trying to figure out, where are credentials stored once they are defined in the UI in K8s? 
I would like to be able to see if new ones are added but cant find them

**Comment by sebastien-prudhomme** [comment]
Hi @danielstankw, under /data/api.json by default. You need to enable persistence if you don't want to lose credentials. In the latest versions there is also an env variable to store them in the database.

**Comment by danielstankw** [comment]
Thank you for the help!
